[project]
name = "sulfur-oil-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "rich>=14.1.0",
    "unitypy>=1.23.0",
]
